### ISSUE TITLE
Inefficiencies

### ISSUE THREAD

**Issue by ghost** [CraftTogether/chat-bridge#1]
In DIscordMessageSender, a new thread is used to send a webhook, this is highly inefficient, spinning up a new thread on every message would be highly resource intensive and would be slower than actually just sending a webhook without it.

The webhook should not take too much time to send, and if it does a threadpool should be initialised upon the plugin being loaded, this will therefore means threads aren't created each message and instead reused.

**Comment by m5rian** [comment]
Oh yeah I know what you mean. I had some weird exceptions when not doing this with bukkit. I will take a lookt at.

**Comment by ghost** [comment]
Alright I fixed it for you
