### ISSUE TITLE
Server statistics in channel info

### ISSUE THREAD

**Issue by ghost** [CraftTogether/chat-bridge#13]
Add minecraft server statistics in the bridge channel info for both IRC and discord

**Comment by ghost** [comment]
@M5rian JDA is throwing a weird error when attempting to do this, and for some reason it is working for IRC sorta but for some reason it doesn't appear

Would you mind attempting to get it working for discord?

**Comment by m5rian** [comment]
sure

**Comment by ghost** [comment]
@M5rian as it is being rate limited, should this be done on an event basis, aka every 5-10 mins update the channel info?

**Comment by m5rian** [comment]
This might be the way, because the rate limit is high af

**Comment by ghost** [comment]
> This might be the way, because the rate limit is high af

How large is the rate limit?

**Comment by ghost** [comment]
hopefully implemented successfully in commit a19638f30d999aa7de254ac84af15e7d1b48c38b
