### ISSUE TITLE
okhttp3 connect leak

### ISSUE THREAD

**Issue by ghost** [CraftTogether/chat-bridge#4]
logger produced:
[okhttp3.OkHttpClient] A connection to https://discord.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by ghost** [comment]
could not reproduce with latest version -> closing issue for now

**Comment by ghost** [comment]
@M5rian I am awaiting this to be patched!!!

**Comment by m5rian** [comment]
Right now I'm waiting for the stacktrace...

**Comment by ghost** [comment]
This problem seems to come in and out, it might be dependent on a specific event which happens which is rare for the bridge... for example how it is started.

**Comment by ghost** [comment]
It is not a major issue, therefore we will deal with it when it comes up again

**Comment by ghost** [comment]
@M5rian during testing commit d4ebe2bb8fa43e56291a6b457c6e7c6ef4ef5aff I had this:
![image](https://user-images.githubusercontent.com/88213045/150135104-7a47b472-6bad-4be6-b58a-317de100daa6.png)

**Comment by ghost** [comment]
seems like commit 781010e53397e482ecd409294659ee88e050c02a fixed the issue

Thanks -> closing issue (hopefully for good now)
